
#ota,xip,lwip, function config
with_lwip := 0
with_xip := 1
with_ota := 1
with_rom := 1

__CONFIG_USE_PREBUILT_LIBSC_ASSISTANT := y
__CONFIG_USE_PREBUILT_LIBWPA := y
__CONFIG_USE_PREBUILT_LIBWPAS := y
__CONFIG_USE_PREBUILT_LIBWLAN := y
__CONFIG_USE_PREBUILT_LIBXRWIRELESS := y
__CONFIG_USE_PREBUILT_LIBNET80211 := y





